#!/usr/bin/env bash
set -euo pipefail

# ═══════════════════════════════════════════════════════════════
#  deploy-agent-ops.sh
#  One-command setup: your own AI Agent Operations Center
#  Inspired by 45dgof8 — Humbly offered for replication
# ═══════════════════════════════════════════════════════════════

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'

info()  { echo -e "${CYAN}[INFO]${NC}  $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
err()   { echo -e "${RED}[ERR]${NC}   $1"; }
header(){ echo -e "\n${BOLD}━━━ $1 ━━━${NC}\n"; }

# ── Config ────────────────────────────────────────────────────
OWNER_EMAIL="${1:-you@example.com}"
INSTALL_DIR="$HOME/agent-ops"
N8N_DIR="$INSTALL_DIR/n8n"
CMD_DIR="$INSTALL_DIR/command-center"
BIN_DIR="$HOME/bin"
N8N_PORT=5678
CMD_PORT=42042

# ── Restore Point ─────────────────────────────────────────
RESTORE_DIR=""

# ── Docker Helper (handles permission issues automatically) ──
run_docker() {
  local desc="$1"
  shift
  if "$@" 2>/dev/null; then
    return 0
  fi
  warn "Docker permission issue. Trying sg docker..."
  if sg docker -c "$*" 2>/dev/null; then
    return 0
  fi
  warn "Trying with sudo..."
  if sudo "$@" 2>/dev/null; then
    return 0
  fi
  err "Cannot run: $*"
  err "Try: sudo usermod -aG docker $USER && log out and back in"
  exit 1
}


create_restore_point() {
  local ts=$(date +%Y%m%d-%H%M%S)
  RESTORE_DIR="$INSTALL_DIR/restore/$ts"
  mkdir -p "$RESTORE_DIR"
  
  header "Creating Restore Point"
  echo -e "  ${CYAN}Backup:${NC} $RESTORE_DIR"

  # Save current crontab
  crontab -l 2>/dev/null > "$RESTORE_DIR/crontab.before" || true

  # Save docker state
  docker ps --format '{{.Names}}' 2>/dev/null > "$RESTORE_DIR/containers.before" || true

  # Save cloudflared config if exists
  [ -f $HOME/.cloudflared/config.yml ] && cp $HOME/.cloudflared/config.yml "$RESTORE_DIR/cloudflared-config.before" 2>/dev/null || true

  # Save existing n8n config if exists
  [ -f "$N8N_DIR/docker-compose.yml" ] && cp "$N8N_DIR/docker-compose.yml" "$RESTORE_DIR/docker-compose.before" || true

  # Generate restore script
  cat > "$RESTORE_DIR/undo.sh" << 'UNDOEOF'
#!/usr/bin/env bash
# Restore script generated by deploy-agent-ops
set -e
RESTORE="$(cd "$(dirname "$0")" && pwd)"
echo "Restoring from: $RESTORE"

# Stop and remove n8n
if [ -f n8n-dir/docker-compose.yml ]; then
  cd n8n-dir && docker compose down -v 2>/dev/null || true
fi

# Restore cloudflared
[ -f "$RESTORE/cloudflared-config.before" ] && cp "$RESTORE/cloudflared-config.before" $HOME/.cloudflared/config.yml 2>/dev/null || true

# Restore crontab
[ -f "$RESTORE/crontab.before" ] && crontab "$RESTORE/crontab.before" 2>/dev/null || true

# Restore docker-compose
[ -f "$RESTORE/docker-compose.before" ] && cp "$RESTORE/docker-compose.before" . || true

echo "Restore complete. Review changes in $RESTORE"
echo "Run: rm -rf agent-ops  # to fully remove installation"
UNDOEOF

  chmod +x "$RESTORE_DIR/undo.sh"
  
  # Fix the n8n-dir placeholder in undo script
  sed -i "s|n8n-dir|$N8N_DIR|g" "$RESTORE_DIR/undo.sh"
  
  ok "Restore point saved. To undo: bash $RESTORE_DIR/undo.sh"
}

# ── Security Check ──────────────────────────────────────────
security_check() {
  header "Security Check"
  echo -e "  This script exposes services to the internet."
  echo -e "  ${YELLOW}May I check your system for common risks? (Y/N)${NC}"
  read -r answer < /dev/tty
  case "$answer" in
    [Yy]*)
      echo ""
      local issues=0

      # Check open ports
      if command -v ss &>/dev/null; then
        local listening=$(ss -tln | grep -cE "0\.0\.0\.0:|:::")
        if [ "$listening" -gt 10 ]; then
          warn "You have $listening open ports. Consider a firewall."
          issues=$((issues+1))
        else
          ok "Ports: $listening listening services — looks clean"
        fi
      fi

      # Check firewall
      if command -v ufw &>/dev/null; then
        local ufw_status=$(sudo ufw status 2>/dev/null | grep -c active || echo 0)
        if [ "$ufw_status" -eq 0 ]; then
          warn "UFW firewall is inactive. Consider enabling it."
          issues=$((issues+1))
        else
          ok "UFW firewall is active"
        fi
      elif command -v iptables &>/dev/null; then
        ok "iptables detected (checking rules manually not supported)"
      else
        warn "No firewall tool detected (ufw/iptables)"
      fi

      # Check Docker socket permissions
      if [ -S /var/run/docker.sock ]; then
        local sock_perms=$(stat -c '%a' /var/run/docker.sock 2>/dev/null || echo "unknown")
        if [ "$sock_perms" = "666" ] || [ "$sock_perms" = "777" ]; then
          warn "Docker socket is world-writable ($sock_perms). Anyone on this machine can run containers."
          issues=$((issues+1))
        else
          ok "Docker socket permissions: $sock_perms"
        fi
      fi

      # Check if root
      if [ "$EUID" = "0" ]; then
        warn "Running as root. Consider using a regular user with sudo."
        issues=$((issues+1))
      fi

      # Check passwordless sudo
      if sudo -n true 2>/dev/null; then
        warn "Passwordless sudo is enabled."
        issues=$((issues+1))
      fi

      # Check SSH config
      if [ -f /etc/ssh/sshd_config ]; then
        if grep -q 'PermitRootLogin yes' /etc/ssh/sshd_config 2>/dev/null; then
          warn "Root login via SSH is permitted."
          issues=$((issues+1))
        fi
        if grep -q 'PasswordAuthentication yes' /etc/ssh/sshd_config 2>/dev/null; then
          warn "Password authentication over SSH is enabled."
        fi
      fi

      echo ""
      if [ "$issues" -gt 0 ]; then
        warn "Found $issues potential issue(s). Review the warnings above."
      else
        ok "No obvious security issues found."
      fi

      echo ""
      echo -e "  ${YELLOW}Continue with installation? (Y/N)${NC}"
      read -r proceed < /dev/tty
      case "$proceed" in
        [Yy]*) ok "Proceeding with installation..." ;;
        *) echo -e "  ${RED}Installation cancelled by user.${NC}"; exit 0 ;;
      esac
      ;;
    *)
      warn "Skipped security check. Proceed at your own risk."
      echo -e "  ${YELLOW}Continue? (Y/N)${NC}"
      read -r proceed2 < /dev/tty
      case "$proceed2" in
        [Yy]*) ok "Proceeding..." ;;
        *) echo -e "  ${RED}Installation cancelled.${NC}"; exit 0 ;;
      esac
      ;;
  esac
}

# ── Requirements ──────────────────────────────────────────────
check_requirements() {
  header "Checking System Requirements"
  local pass=true

  if ! command -v docker &>/dev/null; then
    err "Docker not found. Installing..."
    curl -fsSL https://get.docker.com | bash
    sudo usermod -aG docker "$USER"
    warn "You may need to log out and back in for Docker group to take effect"
    ok "Docker installed"
  else
    ok "Docker: $(docker --version)"
  fi

  if ! docker compose version &>/dev/null && ! docker-compose --version &>/dev/null; then
    err "Docker Compose not found"
    exit 1
  else
    ok "Docker Compose: $(docker compose version 2>/dev/null || docker-compose --version 2>/dev/null)"
  fi

  if command -v python3 &>/dev/null; then
    ok "Python3: $(python3 --version)"
  else
    err "Python3 not found. Install it first."
    exit 1
  fi

  local mem=""
  if command -v free &>/dev/null; then
    mem=$(free -m | awk '/^Mem:/{print $2}')
  elif [ -f /proc/meminfo ]; then
    mem=$(awk '/MemTotal/{printf "%d", $2/1024}' /proc/meminfo)
  fi
  if [ -z "$mem" ] || [ "$mem" -eq 0 ] 2>/dev/null; then
    warn "Could not detect RAM"
  elif [ "$mem" -lt 4000 ]; then
    warn "Low RAM: ${mem}MB. n8n + agents may run slow (min 4GB recommended)"
  else
    ok "RAM: ${mem}MB"
  fi

  local disk=$(df -m "$HOME" | awk 'NR==2{print $4}')
  if [ "$disk" -lt 5120 ]; then
    warn "Low disk space: ${disk}MB. Need at least 5GB free"
  else
    ok "Disk: ${disk}MB free"
  fi
}

# ── Directory Structure ───────────────────────────────────────
setup_dirs() {
  header "Creating Directory Structure"
  mkdir -p "$N8N_DIR" "$CMD_DIR" "$BIN_DIR"
  ok "Directories created under $INSTALL_DIR"
}

# ── Deploy n8n ────────────────────────────────────────────────
deploy_n8n() {
  header "Deploying n8n (Workflow Engine)"

  if [ -f "$N8N_DIR/docker-compose.yml" ]; then
    warn "n8n already configured. Skipping."
    return
  fi

  cat > "$N8N_DIR/docker-compose.yml" <<EOF
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-local
    restart: unless-stopped
    ports:
      - "$N8N_PORT:5678"
    environment:
      - N8N_HOST=localhost:$N8N_PORT
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - N8N_METRICS=false
      - WEBHOOK_URL=http://localhost:$N8N_PORT/
      - N8N_ENCRYPTION_KEY=$(openssl rand -hex 24)
      - N8N_USER_FOLDER=/home/node/.n8n
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
EOF

  # Check if port is free
  if ss -tln 2>/dev/null | grep -q ":$N8N_PORT "; then
    warn "Port $N8N_PORT already in use. n8n may already be running."
  fi

  info "Starting n8n..."
  cd "$N8N_DIR" && run_docker "docker compose" docker compose up -d

  # Wait for n8n to be ready (up to 60s)
  info "Waiting for n8n to be ready..."
  local wait=0
  while [ $wait -lt 60 ]; do
    if curl -s -o /dev/null -w "%{http_code}" "http://localhost:$N8N_PORT/healthz" 2>/dev/null | grep -q 200; then
      ok "n8n running at http://localhost:$N8N_PORT"
      break
    fi
    sleep 2
    wait=$((wait+2))
  done
  if [ $wait -ge 60 ]; then
    err "n8n not responding after 60s. Check: run_docker docker logs n8n-local"
    exit 1
  fi
}

# ── Create Owner Account ──────────────────────────────────────
create_owner() {
  header "Creating n8n Owner Account"
  local cookie=$(mktemp)
  local user_resp=$(curl -s -c "$cookie" "http://localhost:$N8N_PORT/rest/owner/setup" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$OWNER_EMAIL\",\"firstName\":\"Agent\",\"lastName\":\"Ops\",\"password\":\"changeme123\"}" 2>/dev/null)

  if echo "$user_resp" | grep -q "alreadySetup"; then
    warn "Owner already set up. Skipping."
  else
    ok "Owner account created: $OWNER_EMAIL / changeme123"
  fi
  rm -f "$cookie"
}

# ── Create MCP API Key ────────────────────────────────────────
create_mcp_key() {
  header "Creating n8n API Key for MCP"
  local mcp_key=""

  # Try to get existing key or create one
  local login_resp=$(curl -s -c /tmp/n8n-cookies.txt \
    "http://localhost:$N8N_PORT/rest/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$OWNER_EMAIL\",\"password\":\"changeme123\"}")

  local api_resp=$(curl -s -b /tmp/n8n-cookies.txt \
    "http://localhost:$N8N_PORT/rest/api-keys" \
    -H "Content-Type: application/json")

  if echo "$api_resp" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('data',[{}])[0].get('apiKey',''))" 2>/dev/null | grep -q .; then
    mcp_key=$(python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('data',[{}])[0].get('apiKey',''))" <<< "$api_resp")
    ok "Using existing API key"
  else
    local create_resp=$(curl -s -b /tmp/n8n-cookies.txt -X POST \
      "http://localhost:$N8N_PORT/rest/api-keys" \
      -H "Content-Type: application/json" \
      -d '{"label":"opencode-mcp"}')
    mcp_key=$(python3 -c "import sys,json; print(json.load(sys.stdin).get('data',{}).get('apiKey',''))" <<< "$create_resp" 2>/dev/null)
    ok "API key created"
  fi

  echo "$mcp_key" > "$INSTALL_DIR/n8n-api-key.txt"
  info "API key saved to $INSTALL_DIR/n8n-api-key.txt"
}

# ── Install cloudflared Tunnel ────────────────────────────────
setup_tunnel() {
  header "Setting up Cloudflare Tunnel (HTTPS access)"

  if command -v cloudflared &>/dev/null; then
    ok "cloudflared already installed: $(cloudflared --version)"
  else
    info "Installing cloudflared..."
    curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /tmp/cloudflared
    chmod +x /tmp/cloudflared
    sudo mv /tmp/cloudflared /usr/local/bin/cloudflared
    ok "cloudflared installed"
  fi

  # Start tunnel
  local tunnel_log="$INSTALL_DIR/tunnel.log"
  nohup cloudflared tunnel --url "http://localhost:$N8N_PORT" > "$tunnel_log" 2>&1 &
  TUNNEL_PID=$!
  echo "$TUNNEL_PID" > "$INSTALL_DIR/tunnel.pid"
  sleep 4

  local tunnel_url=$(grep -oP 'https://[a-zA-Z0-9.-]+\.trycloudflare\.com' "$tunnel_log" 2>/dev/null | head -1)
  if [ -n "$tunnel_url" ]; then
    ok "Tunnel URL: $tunnel_url"
    echo "$tunnel_url" > "$INSTALL_DIR/tunnel-url.txt"
  else
    warn "Tunnel starting... check later: cat $tunnel_log"
  fi
}

# ── Install Python Dependencies ───────────────────────────────
install_python_deps() {
  header "Installing Python Packages"
  pip3 install --user --break-system-packages numpy 2>/dev/null && ok "numpy installed" || warn "numpy install skipped (not critical)"
  ok "Python dependencies ready"
}

# ── Install Generator Scripts ────────────────────────────────
install_scripts() {
  header "Installing Generator Scripts"

  if [ ! -f "$BIN_DIR/generate-track.py" ]; then
    info "Downloading generator scripts..."
    curl -fsSL "https://raw.githubusercontent.com/008Amonra/45dgof8/main/generate-track.py" -o "$BIN_DIR/generate-track.py" 2>/dev/null || warn "Could not fetch scripts from GitHub. They will be missing."
  fi

  chmod +x "$BIN_DIR"/*.py 2>/dev/null || true
  ok "Scripts ready in $BIN_DIR"
}

# ── Command Center Dashboard ─────────────────────────────────
deploy_dashboard() {
  header "Building Command Center Dashboard"

  cat > "$CMD_DIR/server.py" <<'DASHEOF'
import http.server, json, subprocess, os, socket, time

PORT = int(os.environ.get("CMD_PORT", "42042"))
HTML = """
<!DOCTYPE html><html><head><meta charset="UTF-8">
<meta http-equiv="refresh" content="15">
<title>Agent Ops Center</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:'Courier New',monospace;background:#0a0a0f;color:#e0e0e0;padding:20px}
  h1{color:#00ff88;font-size:1.5rem;margin-bottom:20px;border-bottom:1px solid #333;padding-bottom:10px}
  .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}
  .card{background:#12121a;border:1px solid #2a2a3a;border-radius:8px;padding:16px}
  .card h2{font-size:0.9rem;color:#888;margin-bottom:8px}
  .status{font-size:1.2rem;font-weight:bold}
  .up{color:#00ff88}
  .down{color:#ff4444}
  .url{color:#4488ff;font-size:0.8rem;margin-top:4px;word-break:break-all}
  .error{color:#ff8844;font-size:0.8rem;margin-top:4px}
  .footer{margin-top:20px;padding-top:10px;border-top:1px solid #333;font-size:0.75rem;color:#666}
</style></head><body>
<h1>🤖 Agent Operations Center</h1>
<div class="grid" id="grid">Loading...</div>
<div class="footer">45dgof8 Agent Ops • auto-refresh every 15s</div>
<script>
setInterval(async()=>{
  try{
    const r=await fetch('/status'); const d=await r.json();
    document.getElementById('grid').innerHTML=d.cards.map(c=>
      '<div class=card><h2>'+c.name+'</h2>'+
      '<div class="status '+(c.ok?'up':'down')+'">'+(c.ok?'● RUNNING':'○ STOPPED')+'</div>'+
      (c.url?'<div class=url>'+c.url+'</div>':'')+
      (c.error?'<div class=error>'+c.error+'</div>':'')+
    '</div>').join('');
  }catch(e){}
});
fetch('/status').then(r=>r.json()).then(d=>{
  document.getElementById('grid').innerHTML=d.cards.map(c=>
    '<div class=card><h2>'+c.name+'</h2>'+
    '<div class="status '+(c.ok?'up':'down')+'">'+(c.ok?'● RUNNING':'○ STOPPED')+'</div>'+
    (c.url?'<div class=url>'+c.url+'</div>':'')+
    (c.error?'<div class=error>'+c.error+'</div>':'')+
  '</div>').join('');
});
</script></body></html>
"""

def check_port(p):
  with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    return s.connect_ex(('localhost', p)) == 0

class Handler(http.server.BaseHTTPRequestHandler):
  def do_GET(self):
    if self.path == '/status':
      services = [
        ("n8n Workflow Engine", 5678, "http://localhost:5678"),
        ("Command Center", PORT, f"http://localhost:{PORT}"),
      ]
      cards = []
      for name, port, url in services:
        cards.append({"name": name, "ok": check_port(port), "url": url})
      self.send_response(200)
      self.send_header('Content-Type', 'application/json')
      self.send_header('Access-Control-Allow-Origin', '*')
      self.end_headers()
      self.wfile.write(json.dumps({"cards": cards}).encode())
    else:
      self.send_response(200)
      self.send_header('Content-Type', 'text/html')
      self.end_headers()
      self.wfile.write(HTML.encode())

http.server.HTTPServer(('0.0.0.0', PORT), Handler).serve_forever()
DASHEOF

  # Start dashboard
  local pid_file="$INSTALL_DIR/dashboard.pid"
  nohup python3 "$CMD_DIR/server.py" > "$INSTALL_DIR/dashboard.log" 2>&1 &
  echo $! > "$pid_file"
  sleep 1

  if ps -p $(cat "$pid_file") &>/dev/null; then
    ok "Dashboard running at http://localhost:$CMD_PORT"
  else
    warn "Dashboard may not have started. Check: cat $INSTALL_DIR/dashboard.log"
  fi
}

# ── Print Summary ─────────────────────────────────────────────
print_summary() {
  local tunnel_url=$(cat "$INSTALL_DIR/tunnel-url.txt" 2>/dev/null || echo "starting...")

  header "Setup Complete!"
  echo -e "${GREEN}════════════════════════════════════════════${NC}"
  echo -e "  ${BOLD}Your Agent Operations Center${NC}"
  echo -e "${GREEN}════════════════════════════════════════════${NC}"
  echo ""
  echo -e "  ${CYAN}n8n:${NC}         http://localhost:$N8N_PORT"
  echo -e "  ${CYAN}Dashboard:${NC}   http://localhost:$CMD_PORT"
  echo -e "  ${CYAN}Tunnel:${NC}      $tunnel_url"
  echo ""
  echo -e "  ${YELLOW}─── What now? ───${NC}"
  echo -e ""
  echo -e "  ${GREEN}1${NC} Open http://localhost:$N8N_PORT in your browser"
  echo -e "     Create an account (your local n8n instance)"
  echo -e ""
  echo -e "  ${GREEN}2${NC} Set a strong password in n8n Settings"
  echo -e "     The tunnel exposes n8n to the internet"
  echo -e ""
  echo -e "  ${GREEN}3${NC} Import or build a workflow"
  echo -e "     Example: trigger → AI → Telegram → done"
  echo -e ""
  echo -e "  ${GREEN}4${NC} Open the Dashboard: http://localhost:$CMD_PORT"
  echo -e "     See service status at a glance"
  echo -e ""
  echo -e "  ${GREEN}5${NC} Generate your first AI video:"
  echo -e "     python3 $BIN_DIR/generate-race-video.py"
  echo -e ""
  echo -e "  ${GREEN}6${NC} Generate your first AI music track:"
  echo -e "     python3 $BIN_DIR/generate-race-audio.py"
  echo ""
  echo -e "  ${YELLOW}─── Commands ───${NC}"
  echo -e "  Config files: $INSTALL_DIR/"
  echo -e "  Scripts:      $BIN_DIR/"
  echo ""
  echo -e "  ${YELLOW}Stop everything:${NC}"
  echo -e "    cd $N8N_DIR && docker compose down"
  echo -e "    kill \$(cat $INSTALL_DIR/tunnel.pid) 2>/dev/null"
  echo -e "    kill \$(cat $INSTALL_DIR/dashboard.pid) 2>/dev/null"
  echo ""
  echo -e "  ${YELLOW}Start again:${NC}"
  echo -e "    cd $N8N_DIR && docker compose up -d"
  echo -e "    bash $0"
  echo ""
  echo -e "  ${YELLOW}Restore point:${NC}"
  echo -e "    bash $RESTORE_DIR/undo.sh"
  echo ""
  echo -e "  ${YELLOW}Replicate on another machine:${NC}"
  echo -e "    Copy deploy-agent-ops.sh and run it again"
  echo ""
  echo -e "  ${YELLOW}Support / questions:${NC}"
  echo -e "    45dgof8.com/how-to-replicate.html"
  echo ""
  echo -e "${GREEN}════════════════════════════════════════════${NC}"
}

# ── Main ──────────────────────────────────────────────────────
main() {
  clear
  echo ""
  echo -e "${BOLD}${CYAN}   ╔══════════════════════════════════════╗${NC}"
  echo -e "${BOLD}${CYAN}   ║   AI Agent Ops Center — Auto Setup   ║${NC}"
  echo -e "${BOLD}${CYAN}   ╚══════════════════════════════════════╝${NC}"
  echo ""

  security_check
  check_requirements
  create_restore_point
  setup_dirs
  deploy_n8n
  create_owner
  create_mcp_key
  setup_tunnel
  install_python_deps
  install_scripts
  deploy_dashboard
  print_summary
}

main
