@echo off
REM ═══════════════════════════════════════════════════
REM  deploy-agent-ops.bat
REM  AI Agent Ops Center — Windows Setup
REM  Inspired by 45dgof8
REM ═══════════════════════════════════════════════════

setlocal enabledelayedexpansion
set OWNER_EMAIL=%1
if "%OWNER_EMAIL%"=="" set OWNER_EMAIL=you@example.com
set INSTALL_DIR=%USERPROFILE%\agent-ops
set N8N_DIR=%INSTALL_DIR%\n8n

echo.
echo ╔═══════════════════════════════════════════════════╗
echo ║   AI Agent Ops Center — Windows Setup            ║
echo ╚═══════════════════════════════════════════════════╝
echo.
echo Email: %OWNER_EMAIL%
echo Install: %INSTALL_DIR%
echo.


REM ── Security Check ─────────────────────────────────────
echo.
echo [SECURITY] Checking your system...
echo.
set /p ans="May I check your system for common risks? (Y/N): "
if /i not "!ans!"=="Y" goto :skip_sec
echo.
set issues=0

REM Check if running as admin
net session >nul 2>&1
if !errorlevel! equ 0 (
    echo   ! WARNING: Running as Administrator. Consider using a standard user.
    set /a issues+=1
)

REM Check Docker status
docker info >nul 2>&1
if !errorlevel! neq 0 (
    echo   ! WARNING: Docker is not running.
    set /a issues+=1
)

REM Check Windows Defender
powershell -Command "if((Get-MpComputerStatus).RealTimeProtectionEnabled){echo   OK Windows Defender is active} else {echo   ! WARNING: Real-time protection is OFF}"
if !issues! gtr 0 (
    echo.
    echo   Found !issues! potential issue^(s^). Review warnings above.
) else (
    echo   No obvious security issues found.
)
echo.
set /p proceed="Continue with installation? (Y/N): "
if /i not "!proceed!"=="Y" (
    echo   Installation cancelled.
    pause
    exit /b
)
goto :cont_sec
:skip_sec
echo   Skipped security check. Proceed at your own risk.
set /p proceed2="Continue? (Y/N): "
if /i not "!proceed2!"=="Y" (
    echo   Installation cancelled.
    pause
    exit /b
)
:cont_sec
echo.



REM ---- Restore Point -------------------------------------------------
echo.
echo [RESTORE] Creating restore point...
set ts=%DATE:~-4,4%%DATE:~-10,2%%DATE:~-7,2%-%TIME:~0,2%%TIME:~3,2%%TIME:~6,2%
set ts=%ts: =0%
set RESTORE_DIR=%INSTALL_DIR%\restore\%ts%
if not exist "%RESTORE_DIR%" mkdir "%RESTORE_DIR%"

REM Save docker state
docker ps --format "{{.Names}}" > "%RESTORE_DIR%\containers.before" 2>nul

REM Save existing config
if exist "%N8N_DIR%\docker-compose.yml" copy "%N8N_DIR%\docker-compose.yml" "%RESTORE_DIR%\docker-compose.before" >nul

REM Generate undo script
(
echo @echo off
echo REM Undo script generated by deploy-agent-ops
echo set RESTORE_DIR=%%~dp0
echo echo Restoring from: %%RESTORE_DIR%%
echo.
echo REM Stop and remove n8n
echo if exist "%N8N_DIR%\docker-compose.yml" (
echo   cd /d "%N8N_DIR%"
echo   docker compose down -v 2^>nul
echo )
echo.
echo REM Restore docker-compose
echo if exist "%%RESTORE_DIR%%\docker-compose.before" (
echo   copy "%%RESTORE_DIR%%\docker-compose.before" "%N8N_DIR%\docker-compose.yml" ^>nul
echo )
echo.
echo echo Restore complete.
) > "%RESTORE_DIR%\undo.bat"

echo   Restore point: %RESTORE_DIR%
echo   To undo: %RESTORE_DIR%\undo.bat
echo.
REM ── Step 1: Check Docker ──
echo [1/6] Checking Docker...
docker --version >nul 2>&1
if %errorlevel% neq 0 (
    echo   ! Docker Desktop not found.
    echo   Download from: https://www.docker.com/products/docker-desktop/
    echo   Install, start it, then run this script again.
    pause
    exit /b
) else (
    echo   OK Docker Desktop installed
)

REM ── Step 2: Create n8n ──
echo. & echo [2/6] Setting up n8n...
if not exist "%N8N_DIR%" mkdir "%N8N_DIR%"

REM Generate a random encryption key using PowerShell
for /f %%i in ('powershell -Command "[System.Convert]::ToBase64String((New-Object byte[] 32))"') do set ENCRYPT_KEY=%%i

(
echo version: "3.8"
echo services:
echo   n8n:
echo     image: docker.n8n.io/n8nio/n8n:latest
echo     container_name: n8n-local
echo     restart: unless-stopped
echo     ports:
echo       - "5678:5678"
echo     environment:
echo       - N8N_HOST=localhost:5678
echo       - N8N_PROTOCOL=http
echo       - N8N_PORT=5678
echo       - WEBHOOK_URL=http://localhost:5678/
echo       - N8N_ENCRYPTION_KEY=%ENCRYPT_KEY%
echo       - GENERIC_TIMEZONE=UTC
echo     volumes:
echo       - n8n_data:/home/node/.n8n
echo volumes:
echo   n8n_data:
) > "%N8N_DIR%\docker-compose.yml"

cd /d "%N8N_DIR%"
docker compose up -d
echo   n8n starting... wait 5 seconds
timeout /t 5 /nobreak >nul
echo   Open http://localhost:5678 in your browser to create account

REM ── Step 3: cloudflared ──
echo. & echo [3/6] Installing cloudflared tunnel...
if not exist "%INSTALL_DIR%\cloudflared.exe" (
    bitsadmin /transfer download-cloudflared /download /priority foreground "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" "%INSTALL_DIR%\cloudflared.exe" >nul 2>&1
    if !errorlevel! neq 0 (
        curl -fsSL -o "%INSTALL_DIR%\cloudflared.exe" "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe"
    )
    echo   cloudflared downloaded
) else (
    echo   cloudflared already installed
)

echo   Starting tunnel (press Ctrl+C to stop)...
echo   Use this command to start tunnel:
echo   "%INSTALL_DIR%\cloudflared.exe" tunnel --url http://localhost:5678
echo.
echo   The tunnel URL will appear in the window.
echo   Save it — you'll need it to access n8n from the web.

REM ── Step 4: Python ──
echo. & echo [4/6] Checking Python...
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo   ! Python not found.
    echo   Download from: https://www.python.org/downloads/
    echo   CHECK "Add Python to PATH" during install!
) else (
    echo   OK Python found
    python -m pip install --user numpy >nul 2>&1
    echo   numpy installed
)

REM ── Step 5: FFmpeg ──
echo. & echo [5/6] Checking FFmpeg...
ffmpeg -version >nul 2>&1
if %errorlevel% neq 0 (
    echo   ! FFmpeg not found.
    echo   Download from: https://ffmpeg.org/download.html
    echo   Add to PATH or place ffmpeg.exe in %INSTALL_DIR%
) else (
    echo   OK FFmpeg found
)

REM ── Step 6: Dashboard ──
echo. & echo [6/6] Creating Command Center...
if not exist "%INSTALL_DIR%\command-center" mkdir "%INSTALL_DIR%\command-center"

(
echo import http.server, json, socket
echo PORT = 42042
echo HTML = """^<!DOCTYPE html^>...^"""
echo ^
echo def check_port(p^):
echo   with socket.socket(socket.AF_INET, socket.SOCK_STREAM^) as s:
echo     return s.connect_ex(('localhost', p^)^) == 0
echo ^
echo class Handler(http.server.BaseHTTPRequestHandler^):
echo   def do_GET(self^):
echo     if self.path == '/status':
echo       cards = [{"name": "n8n", "ok": check_port(5678^), "url": "http://localhost:5678"}]
echo       self.send_response(200^)
echo       self.send_header('Content-Type', 'application/json'^)
echo       self.end_headers(^)
echo       self.wfile.write(json.dumps({"cards": cards}^).encode(^)^)
echo     else:
echo       self.send_response(200^)
echo       self.send_header('Content-Type', 'text/html'^)
echo       self.end_headers(^)
echo       self.wfile.write(HTML.encode(^)^)
echo ^
echo http.server.HTTPServer(('0.0.0.0', PORT^), Handler^.serve_forever(^)
) > "%INSTALL_DIR%\command-center\server.py"

echo.
echo ====================================================
echo   Setup Complete!
echo ====================================================
echo.
echo   n8n:        http://localhost:5678
echo   Dashboard:  http://localhost:42042
echo.
echo   --- What now? ---
echo.
echo   1. Open http://localhost:5678 in your browser
echo      Create an account (your local n8n instance)
echo.
echo   2. Set a strong password in n8n Settings
echo      The tunnel exposes n8n to the internet
echo.
echo   3. Import or build a workflow
echo      Example: trigger -^> AI -^> Telegram -^> done
echo.
echo   4. Start the dashboard:
echo      python "%INSTALL_DIR%\command-center\server.py"
echo.
echo   5. Start a tunnel (web access):
echo      "%INSTALL_DIR%\cloudflared.exe" tunnel --url http://localhost:5678
echo.
echo   --- Commands ---
echo.
echo   Stop n8n:
echo     cd /d "%N8N_DIR%" ^&^& docker compose down
echo.
echo   Start n8n again:
echo     cd /d "%N8N_DIR%" ^&^& docker compose up -d
echo.
echo   Restore point:
echo     %RESTORE_DIR%\undo.bat
echo.
echo   Support / questions:
echo     https://45dgof8.com/how-to-replicate.html
echo.
echo ====================================================
pause
